### PR TITLE
Add context query

### PR DESCRIPTION
**Pull request by janvrany**
This PR adds `Z3ContextQuery` as an a way to use custom `Z3Context` (as opposed to using single global one which is still used if no custom one is provided). 

Majority of commits is API cleanup.

### CODE REVIEW

**Comment by shingarov** [comment]
I think this is exactly what we want.

Minor nitpicks:

1. In `4681741` I propose to remove the word *pattern* as both (1) incorrect in particular and (2) contrary to the spirit of Smalltalk-25 in general.  `Query` is the right adjoint of product; as such, it is not a pattern but a construct of categorical algebra.  (I seriously hope I will finalize porting Edward Kmett's implementation of `Query` real soon now™; I did not anticipate it would take the whole summer).
2. What happened to the commit message of `1e45430`?  It abruptly truncates after ">>".
3. In `ec7f38d`, it appears to me that `TestCaseWithZ3Context` would benefit from a class comment explaining its purpose, i.e. giving the explicit answer to the question from which this whole PR started: "Every time I am sitting down to write a new test class, I have in front of me a bunch of tests subclassing from `TestCase`, and a bunch subclassing from `TestCaseWithZ3Context`, and for the life of me I can't figure out whether I am supposed to subclass from one or the other."

**Comment by janvrany** [comment]
Force-pushed to update the PR. 

---

> 1. In `4681741` I propose to remove the word _pattern_ as both (1) incorrect in particular and (2) contrary to the spirit of Smalltalk-25 in general.  `Query` is the right adjoint of product; as such, it is not a pattern but a construct of categorical algebra.  (I seriously hope I will finalize porting Edward Kmett's implementation of `Query` real soon now™; I did not anticipate it would take the whole summer).

Done (4681741 became  0b2f1508 )

> 2. What happened to the commit message of `1e45430`?  It abruptly truncates after ">>".

Ah, I put `#` (as Symbol) in front of selector and git thought it is a comment in commit message
and dropped the line. Fixed (1e45430 became d51472ae1)

> 3. In `ec7f38d`, it appears to me that `TestCaseWithZ3Context` would benefit from a class comment explaining its purpose, i.e. giving the explicit answer to the question from which this whole PR started: "Every time I am sitting down to write a new test class, I have in front of me a bunch of tests subclassing from `TestCase`, and a bunch subclassing from `TestCaseWithZ3Context`, and for the life of me I can't figure out whether I am supposed to subclass from one or the other."

Sure, I forgot to do that. Fixed as well ( ec7f38d became 6248bed99)

**Comment by shingarov** [comment]
One last thing.  Maybe I just need more coffee, but I don't understand "_Use context query in to run tests using dedicated context_".  Use–in?

**Comment by janvrany** [comment]
> One last thing. Maybe I just need more coffee, but I don't understand "_Use context query in to run tests using dedicated context_". Use–in?

No, it's me who needs more coffee. Dropped stray "in" in 347bab3.

**Pull request merged**
