### PR TITLE
Refactor `Tuple`s and introduce `Record`

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Review by shingarov — CHANGES_REQUESTED** [review]
The `shouldNotImplement` is on purpose.  To create "instances of this class that actually hold some data", use `#basicNew`.  The problem with `#new` is that it creates "instances of this class that hold no data".  We discussed this a couple of days ago, when talking about `Point new` giving you `nil@nil` and the problems arising from that.  So, `#new` only makes sense when the class has some "default" element.  Now that I am enumerating in my head all the examples of such "default", they all follow the same pattern: `#new` is always the nullary constructor of an algebra of type (0, m, n,...).  For example, `String` is a free monoid, i.e. a free associative algebra with multiplication `#,` a unit `''`, and a nonempty set of generators (one per Character, or equivalently group them under `#of:` which is what Smalltalk does).  The unit is the neutral element under `#,`, so it makes perfect sense that `#new` returns `''`.

Looking at `Integer`, if we were to regard Integer as an additive group, then it would make sense for `Integer new` to answer 0.  But Integer can be seen as more things than an additive group; for example, it is also a ring, with 1 as the unit under `#*`.  Haha, I just had some fun with sending `#new` to different subclasses of Integer in Pharo — illustrates the trap pretty well.

Interestingly, `1@2` never sends `#new`.  `<primitive:18>` either succeeds, or on the fail path it sends `Point>>x:y:` which calls `#basicNew`.  This I think is better than what happens in `Integer`, and definitely consistent with what we do everywhere across MachineArithmetic (also see how TypedTuples are instantiated in `neoJsonMapping:`)

**Review by shingarov — CHANGES_REQUESTED** [review]
Same observation.
```
^self basicNew term: term type: type
```
and prohibit `#new`

**Comment by janvrany** [comment]
> The shouldNotImplement is on purpose. To create "instances of this class that actually hold some data", use #basicNew.

> Same observation.

OK, got it, I'll update the PR once you're done with your review, except that I'll add a little comment to new that

> To create "instances of this class that actually hold some data", use #basicNew. 

This is in fact a pattern I'm using in Tinyrossa, for instance: https://github.com/janvrany/Tinyrossa/blob/master/src/Tinyrossa/TRCodeGenerator.class.st#L18C1-L26C2

**Comment by shingarov** [comment]
Perfect.  The rest of this PR LGTM, as in, I'll merge as soon as `basicNew` is addressed.
I do have a minor comment on that `RBScanner` stuff, it's trying to be smart and you know what I think about "smart", but that's philosophical so let's ignore it for now.

**Comment by janvrany** [comment]
I just pushed update:
 * dropped [3b22d50](https://github.com/shingarov/MachineArithmetic/pull/188/commits/3b22d50c25777fe56f9d7775c58d1eebec0ef3d0)
 * added 72dddc8 with new `#new`
 * added 3643451 to fix dependencies of MathNotation.

**Comment by shingarov** [comment]
Perfect.

BTW, this thing with `#new` indicates a deeper issue with classes.  Remember how in one conversation in slack, @len juxtaposes "ℤ as a set" vs "ℤ as an additive group" vs "ℤ as a ring" etc.  So if we tried to regard `Integer` as "ℤ in Smalltalk" we would fail, as it would have to respond differently to `#new` based on what's intended.

**Comment by shingarov** [comment]
Also worth noting, is how this seems related to mutability.  Due to how Smalltalk-80 works, `Point>>x:y:` first creates an "empty" instance (`nil@nil`) and then fills it with data.  If it atomically created immutable points (like in Erlang as a _closest_ example), the whole argument would become moot.

**Pull request merged**
