### PR TITLE
Slightly improve the Smalltalk API to Z3 Sets

### PR DESCRIPTION
**Pull request by shingarov**

### CODE REVIEW

**Comment by shingarov** [comment]
@janvrany  I feel we are nearing the limit of our "no math-notation in MachineArithmetic proper" approach.  6a04015 is problematic in that Z3 Set's #∩ etc have nothing to do with Refinements, they are Z3-level and so belong squarely in MachineArithmetic proper: the only reason I am not putting it there is because of the dependency chain, #∩ becomes a valid selector after MathNotation is loaded.

**Comment by janvrany** [comment]
@shingarov 
> I am not putting it there is because of the dependency chain, #∩ becomes a valid selector after MathNotation is loaded.

I think there might be a better solution, I'll have a look later today,

**Comment by janvrany** [comment]
Multiple comments:

> 6a0401511acc70a3dd03b234eb162e563ec8a9b6 is problematic in that Z3 Set's #∩ etc have nothing to do with Refinements,

Yes, but we can follow customary smalltalk convention and implement them as `#intersection:`, `#union:`, `#difference:` and then have these `#∩` in math notation. I went ahead and did this, see https://github.com/janvrany/MachineArithmetic/tree/improve-set
* https://github.com/janvrany/MachineArithmetic/commit/53e61248012b6b8670f6d6c8c617bebd0109b734
* https://github.com/janvrany/MachineArithmetic/commit/6efb809e04970d43ee6fee92b0793990cb2df454
* https://github.com/janvrany/MachineArithmetic/commit/f9dd5d7205bbc300a3c30cdd36910bfd040dc7f2

(feel free to cherry-pick)

---

> @janvrany I feel we are nearing the limit of our "no math-notation in MachineArithmetic proper" approach

Well, according to https://github.com/janvrany/MachineArithmetic/blob/pure-z3/pharo/check-deps.st#L24-L29 it is "no math-notation anywhere". We're already breaking this rule (though it won't be too much work to fix it). But I guess you won't like it so let's update the comment. 

---

```
ensureSet
	self canBeSet ifFalse: [ self error ]
```

I quite dislike using `self error` without giving any message. 

---

I was thinking, why not making a concept of a set in MA more explicit by introducing something like `Z3Set`? Seems easy enough to implement.

**Comment by shingarov** [comment]
> and then have these #∩ in math notation

You are correct.  I need a new brain.  I completely forgot that we can classify them in MathNotation, and put them in Refinements which felt totally bad (having some set operations here and some there without a good reason).

**Comment by shingarov** [comment]
> concept of a set in MA more explicit by introducing something like Z3Set? Seems easy enough to implement.

That's a very big discussion, better suited for `#mathematics` in BsAs-St slack, or even better in-person with Leandro and Luciano.  After 150 years, we finally grew to dislike the Lobachevsky–Dirichlet–Dedekind definition of "a function f is a subset f⊂D×C such that..." well this Z3 definition of sets as bool-valued McCarthy arrays shares the same criticisms.  Yes it's an extremely nice representation, especially for inductive reasoning about infinite sets.  I think it would be worthwhile to make a separate subclass for them as you are proposing; I think it will work, because at McCarthyArray instantiation time you *know* what the domain is, and after that you can't mutate it into something else.

On the other hand, I vaguely recall that trying something similar with the Z3 Datatype API I ran into some problems but I forget what they were.  I think it all boils down to the fundamental question of "are functions indeed Lobachevsky–Dirichlet–Dedekind functions", and in general "what is the nature of definitions in mathematics".  Other immediately-relevant examples are the different definitions of monoids, or in Luciano's system there are classes `Group` and `Ring` which pose the same question about their relationship to groups and rings.

**Comment by shingarov** [comment]
> I quite dislike using self error without giving any message.

This is a discussion of wider scope than this PR.  But if we are here, I think it's like code without a comment.  If execution hit there, and I am staring at the stack trace, an explanatory text adds no additional insight over what's already obvious from the stack.

It's like calling `#assert:` vs `#assert:description:`.

**Comment by shingarov** [comment]
> There are no other senders.

That's because I haven't gotten around to writing them yet (because, submission deadlines blah blah).

One needs the operations of union and intersection of n sets, where n≥0, NOT only n>0.  Otherwise sets form no CPO, that means no Knaster-Tarski, nothing.

> Besides, this avoids accessing global context.

Hmm.  Now that I am digging deeper into it, this looks like a problem at the Z3 API level: it would be much nicer if `mk_set_union()` took a domain sort to allow for _n=0_.  Now one has to special-case `mk_empty_set()` at a level above C.  We shall see when the time comes.  For now I am merging your branch.

**Pull request merged**
