### PR TITLE
[Z3] Add unsigned-comparison selectors

### PR DESCRIPTION
**Pull request by shingarov**
I would prefer something nicer-looking like >₊ but:
1. It would complicate situation with MathNotation, let's wait until unicode-parity;
2. Currently there are "subscripts in ids" (like x₊), let's wait until that stabilizes.

### CODE REVIEW

**Comment by shingarov** [comment]
@janvrany Do these selectors look agreeable to you?

**Comment by shingarov** [comment]
Wow, this breaks St/X...

**Comment by shingarov** [comment]
Ok I've got no idea why this is.  Creating methods with these selectors works A-ok in the St/X browser...

**Comment by janvrany** [comment]
LGTM with my fix for St/X.

**Comment by shingarov** [comment]
So it means, even our *syntax* ("fits on a postcard…") is dialect-specific in non-trivial ways (and I am not talking about extensions like Cuis' `::` or Pharo's `{}`).  Great.  (Not).

**Pull request merged**
