### PR TITLE
Use "Smalltalk makefiles"

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by janvrany** [comment]
Oh! Iceberg just chokes when there's a submodule in directory containing packages like in MA. Nothing works!

@shingarov : I see 2 ways out of this:
  * do not use submodule - that would make it different from what we did in ArchC and Tinyrossa
  * move code to `src` subdirectory - that would make make merging / rebasing of development branches PITA.

**Comment by shingarov** [comment]
> do not use submodule

I must admit I am taking the lazy route here and instead of grinding the granite I am just asking this question: why then doesn't iceberg choke in the case of ArchC?  ArchC also has multiple packages just like MA does.

**Comment by janvrany** [comment]
> why then doesn't iceberg choke in the case of ArchC?

I will not pretend I 100% understand how that thing work but after cursory look at stacktrace:

When one try to register repository in Pharo (for commiting from Pharo) Iceberg proactively looks what packages are checking all subdirectories of "source" directory (the one defined `.project` file). Since in MA source directory is the repository root (unlike in ArchC!), it tries to look into (submodule's) subdirectory `makefiles` and here chokes because commits in makefiles directory are completely unrelated to those of MA itself. Note, that Iceberg largely ignores what's in working copy and work with git commits/trees (but overwrites working copy, trashing all changes you make outside of Pharo!). 

Now, thinking of it I think 'do not use submodule' approach would not work for reasons described above. Have not tried though.

**Comment by shingarov** [comment]
Sorry, I forgot what we said about the status of this.  Is this supposed to get merged, or did we say we wanted to wait about something?

**Comment by janvrany** [comment]
It cannot be merged as of now as it has many conflicts coming from the fact this PR moves files over. 

To minimize impact on your WIP, I suggest following: 
  1. I'll wait for you to commit / merge all pending changes
  2. I'll update the PR based on then-current head
  3. Ideally, we solve the naming of MA-MA package (also renaming)
  4. You'll merge it.
  5. I'll then open PR on projects referring to MA to update makefiles and references:
     - Z3
     - ArchC
     - Tinyrossa
     - MTR
     - ???

**Comment by shingarov** [comment]
Ooooh, you are right — it's not "just" Z3, and those "big" dependents, but also ULD, PIG, Ott, and a bunch of private ones (OttawaLCF, Futamura etc etc etc)

**Comment by janvrany** [comment]
>  it's not "just" Z3, and those "big" dependents

As long as these do not use "smalltalk makefiles" using `pharo-load-local` macro) it should be fine. 

```
...
$(call pharo-load-local, $@, MachineArithmetic,$(MACHINEARITHMETIC_DIR))
...
```

**Comment by shingarov** [comment]
Alright, then what should we call the inner MA then?  "SMT"?  "Z3"?

**Comment by janvrany** [comment]
I would very much prefer just "Z3"

**Comment by shingarov** [comment]
Perfect, we have consensus on Z3.

**Comment by janvrany** [comment]
I have pushed new version of this PR ([2f8a0e4](https://github.com/shingarov/MachineArithmetic/pull/133/commits/2f8a0e47ed82b2959eda5fcfdea38908b25a78a7)). 

Rebasing other branches atop of [2f8a0e4](https://github.com/shingarov/MachineArithmetic/pull/133/commits/2f8a0e47ed82b2959eda5fcfdea38908b25a78a7) "mostly" works - you still need to move *new* packages introduced in these branches to `src` subdirectory (like, `PLE` or `Deduction-Pharo`). 

Here's a little script that automates all this for branches `reflect4` `bounds` `deduction` (adding more is trivial):

```bash
set -ex

git checkout pure-z3
trap 'git checkout pure-z3' EXIT
for branch in reflect4 bounds deduction; do
	git fetch upstream $branch:$branch-atop-pr133
	git checkout $branch-atop-pr133
	git rebase pr/use-smalltalk-makefiles-02

	commit=no
	for pkg_st in */package.st; do
		pkg=$(dirname $pkg_st)
		echo $pkg
		git mv $pkg src
		commit=yes
	done
	if [ "$commit" == "yes" ]; then
		git commit -m 'Move packages to `src` subdirectory'
	fi
	make -C pharo clean all
	make -C stx test
	echo "==== $branch ===="
	ls
	echo "================="
	echo "Press Ctrl-C to abort, any key to continue..."
	read ignored
done
```

**Pull request merged**
