### PR TITLE
Z3 "overhaul"

### PR DESCRIPTION
**Pull request by janvrany**
This is an unfinished, work-in-progress draft of proposed Z3 overhaul. The aim is to give a chance to comment on changes early. 

This draft will be worked on until it reaches a shape ready for merging at which point I'll convert it into normal PR.

### CODE REVIEW

**Review by shingarov — CHANGES_REQUESTED** [review]
This is incorrect.  BitVector, Int etc are sorts, but Sort is not a sort, it's a universe.  In Smalltalk parlance the former would be like classes but Sort is a metaclass.

**Comment by janvrany** [comment]
> This is incorrect. BitVector, Int etc are sorts, but Sort is not a sort, it's a universe. In Smalltalk parlance the former would be like classes but Sort is a metaclass.

Right. I just looked again at Python bindings AST hierarchy (see attached files). I'm thinking of following that, but I guess we may not need to implement all of them. Shall I exclude `FP*`, `Seq*`, `Re*` and `FiniteDomain*`? `AlgebraicNumRef`?

[pyz3-ast-tree.txt](https://github.com/shingarov/MachineArithmetic/files/6387288/pyz3-ast-tree.txt)
[pyz3-ast-tree.pdf](https://github.com/shingarov/MachineArithmetic/files/6387289/pyz3-ast-tree.pdf)
[pyz3-ast-tree-dump.py.txt](https://github.com/shingarov/MachineArithmetic/files/6387290/pyz3-ast-tree-dump.py.txt)

**Comment by shingarov** [comment]
> Shall I exclude FP*, Seq*, Re* and FiniteDomain*?

Whatever you think is the easiest.  It's going to be a while before we need them.  So it really depends on how much work it is to add / exclude them: I was adding the FFIs by hand as I went, but now with your auto-FFI magic I don't know whether it's easier to add or exclude these sorts.

**Comment by janvrany** [comment]
@shingarov 
Just pushed an update, see 22cbd5c. Changes are:
 * reworked AST class hierarchy to loosely follow how Python bindings model things,
 * added generated API,
 * rewritten AST instantiation - identity is not preserved, this will be reinroduced later
 * fixed things here and there to use new generated API to make `IntValueTest >> #testConcat` pass. 

Changes in 22cbd5c show how (straightforward is) to use new generated API. 

There's whole lot to be desired yet, but I feel it is materializing and so far I'm more or less happy how it turned out. 

As to AST class hierarchy, I used `Node` where Python bindings use `Expr` but now I wonder whether `Term` would be better, that is, to have `Z3Term` instead of `Z3Node` (in Python they call it `ExprRef`)?

**Comment by janvrany** [comment]
I just pushed few more commits, moving `Int`, `Real` and `BitVector` over to new generated API. As of now:
```
SUMMARY: 134 run, 46 passed, 2 skipped, 0 failed, 86 errors, test execution time 2.226s
```

**Comment by janvrany** [comment]
I just pushed a major update to this PR. Most of the code has been moved over to new generate API and all but two tests are passing. There are still few things missing before this is ready for review and merge:

  1. Fix remaining two tests (`Z3CAPITest>>#testProve1` and `BoolSymbolTest>>#testUnsat`)
  2. Check for unused code
  3. Update `MachineArithmetic-FFI-Pharo` to contain generated FFIs (and few other support methods)

**Comment by janvrany** [comment]
Another update that makes it working in Pharo too. So now the only remaining bit is to fix `Z3CAPITest>>#testProve1` and `BoolSymbolTest>>#testUnsat`

**Comment by janvrany** [comment]
OK, so I have fixed last two issues and now all tests pass on Pharo. Therefore I marked the PR as ready for review and - eventually - for merging.

**Pull request merged**
